-----------------------------------------------------------
-- Colorscheme:
-----------------------------------------------------------
vim.o.background = "dark"
vim.cmd("highlight clear")
vim.g.colors_name = "archery"
local function set_highlight(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end
-----------------------------------------------------------
-- Syntax Group Names:
-----------------------------------------------------------
set_highlight("Comment", { italic = true, fg = "#535B6F", bg = "NONE" })
set_highlight("Constant", { fg = "#b226c1", bg = "NONE" })
set_highlight("String", { fg = "#7daea3", bg = "NONE" })
set_highlight("Character", { link = "Constant" })
set_highlight("Number", { link = "Constant" })
set_highlight("Boolean", { link = "Constant" })
set_highlight("Float", { link = "Constant" })
set_highlight("Identifier", { fg = "#006596", bg = "NONE" })
set_highlight("Function", { link = "Identifier" })
set_highlight("Statement", { bold = true, fg = "#0088CC", bg = "NONE" })
set_highlight("Conditional", { link = "Statement" })
set_highlight("Repeat", { link = "Statement" })
set_highlight("Label", { link = "Statement" })
set_highlight("Operator", { link = "Statement" })
set_highlight("Keyword", { link = "Statement" })
set_highlight("Exception", { link = "Statement" })
set_highlight("PreProc", { fg = "#F6F9FC", bg = "NONE" })
set_highlight("Include", { link = "PreProc" })
set_highlight("Define", { link = "PreProc" })
set_highlight("Macro", { link = "PreProc" })
set_highlight("PreCondit", { link = "PreProc" })
set_highlight("Type", { fg = "#0088CC", bg = "NONE" })
set_highlight("StorageClass", { link = "Type" })
set_highlight("Structure", { link = "Type" })
set_highlight("Typedef", { link = "Type" })
set_highlight("Special", { fg = "#53586F", bg = "NONE" })
set_highlight("SpecialChar", { link = "Special" })
set_highlight("Tag", { link = "Special" })
set_highlight("Delimiter", { link = "Special" })
set_highlight("SpecialComment", { link = "Special" })
set_highlight("Debug", { link = "Special" })
set_highlight("Underlined", { underline = true, fg = "NONE", bg = "NONE" })
set_highlight("Ignore", { fg = "NONE", bg = "NONE" })
set_highlight("Error", { fg = "#C95F5F", bg = "NONE" })
set_highlight("Todo", { fg = "#EAC06E", bg = "NONE" })
-----------------------------------------------------------
-- Default Highlighting Groups:
-----------------------------------------------------------
set_highlight("Normal", { fg = "#81A3CF", bg = "NONE" })
set_highlight("Visual", { fg = "#fffffe", bg = "#413a7a" })
set_highlight("VisualNOS", { fg = "#F6F9FC", bg = "NONE" })
set_highlight("Cursor", { fg = "#F6F9FC", bg = "#0088CC" })
set_highlight("CursorIM", { fg = "#F6F9FC", bg = "#3B5A7A" })
set_highlight("CursorColumn", { fg = "NONE", bg = "NONE" })
set_highlight("CursorLine", { fg = "NONE", bg = "#1E1E2E" })
set_highlight("CursorLineNr", { fg = "#0088CC", bg = "NONE" })
set_highlight("ErrorMsg", { fg = "#C95F5F", bg = "NONE" })
set_highlight("ModeMsg", { fg = "#81A3CF", bg = "NONE" })
set_highlight("MoreMsg", { fg = "#0088CC", bg = "NONE" })
set_highlight("WarningMsg", { fg = "#F07D30", bg = "NONE" })
set_highlight("Title", { fg = "#0088CC", bg = "NONE" })
set_highlight("Question", { fg = "#0088CC", bg = "NONE" })
set_highlight("SpecialKey", { fg = "#81A3CF", bg = "NONE" })
set_highlight("NonText", { fg = "#F6F9FC", bg = "NONE" })
set_highlight("EndOfBuffer", { fg = "#81A3CF", bg = "NONE" })
set_highlight("Pmenu", { bold = true, fg = "#25272C", bg = "NONE" })
set_highlight("PmenuSel", { bold = true, fg = "#F6F9FC", bg = "#0088CC" })
set_highlight("PmenuSbar", { fg = "NONE", bg = "NONE" })
set_highlight("PmenuThumb", { fg = "NONE", bg = "NONE" })
set_highlight("MatchParen", { fg = "#25272C", bg = "#F6F9FC" })
set_highlight("IncSearch", { fg = "#25272C", bg = "#81A3CF" })
set_highlight("Search", { fg = "#282D34", bg = "#F6F9FC" })
set_highlight("WildMenu", { bold = true, fg = "#F6F9FC", bg = "#0088CC" })
set_highlight("Folded", { bold = true, fg = "#0088CC", bg = "NONE" })
set_highlight("FoldColumn", { fg = "#F6F9FC", bg = "NONE" })
set_highlight("DiffAdd", { fg = "#73BA25", bg = "NONE" })
set_highlight("DiffChange", { fg = "#EAC06E", bg = "NONE" })
set_highlight("DiffDelete", { fg = "#C95F5F", bg = "NONE" })
set_highlight("DiffText", { fg = "#81A3CF", bg = "NONE" })
set_highlight("SpellBad", { fg = "#C95F5F", bg = "NONE" })
set_highlight("SpellCap", { fg = "#F07D30", bg = "NONE" })
set_highlight("SpellLocal", { fg = "#73BA25", bg = "NONE" })
set_highlight("SpellRare", { fg = "#EAC06E", bg = "NONE" })
set_highlight("Directory", { bold = true, fg = "#0088CC", bg = "NONE" })
set_highlight("LineNr", { fg = "#53586F", bg = "NONE" })
set_highlight("VertSplit", { bold = true, fg = "#0088CC", bg = "NONE" })
set_highlight("ColorColumn", { fg = "NONE", bg = "NONE" })
set_highlight("SignColumn", { fg = "#81A3CF", bg = "NONE" })
set_highlight("Conceal", { fg = "#81A3CF", bg = "NONE" })
-----------------------------------------------------------
-- GUI Highlighting Groups:
-----------------------------------------------------------
set_highlight("Menu", { fg = "#53586F", bg = "NONE" })
set_highlight("Scrollbar", { fg = "#53586F", bg = "NONE" })
set_highlight("Tooltip", { fg = "#F6F9FC", bg = "NONE" })
set_highlight("NormalFloat", { fg = "#81A3CF", bg = "NONE" })
set_highlight("FloatBorder", { fg = "#81A3CF", bg = "NONE" })
set_highlight("Sidebar", { fg = "#81A3CF", bg = "NONE" })
set_highlight("SidebarBorder", { fg = "#81A3CF", bg = "NONE" })
-----------------------------------------------------------
-- Tabline:
-----------------------------------------------------------
set_highlight("MiniTablineCurrent", { italic = true, fg = "#0088CC", bg = "NONE" })
set_highlight("MiniTablineVisible", { italic = true, fg = "#535B6F", bg = "NONE" })
set_highlight("MiniTablineHidden", { italic = true, fg = "#535B6F", bg = "NONE" })
set_highlight("MiniTablineModifiedCurrent", { italic = true, fg = "#0088CC", bg = "NONE" })
set_highlight("MiniTablineModifiedVisible", { italic = true, fg = "#535B6F", bg = "NONE" })
set_highlight("MiniTablineModifiedHidden", { italic = true, fg = "#535B6F", bg = "NONE" })
set_highlight("MiniTablineTabpagesSection", { italic = true, fg = "#535B6F", bg = "NONE" })
set_highlight("MiniTablineFill", { italic = true, fg = "#535B6F", bg = "NONE" })
